#!/usr/bin/env python

# Copyright (c) 2019 Alexander Todorov <atodorov@MrSenko.com>

# Licensed under the GPLv3: https://www.gnu.org/licenses/gpl.html

if __name__ == "__main__":
    import sys
    from tcms_tap_plugin import main

    main(sys.argv)
